# Generated by Django 2.1.15 on 2019-12-31 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chubanshe',
            fields=[
                ('jc_id', models.CharField(max_length=10)),
                ('cbs_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cbs_name', models.CharField(max_length=10)),
                ('cbs_kucun', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dinggou',
            fields=[
                ('jc_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cbs_id', models.IntegerField()),
                ('xx_id', models.IntegerField()),
                ('dg_dgliang', models.IntegerField()),
                ('dg_dhliang', models.IntegerField(null=True)),
                ('dg_lyliang', models.IntegerField(null=True)),
                ('chubanshe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_ks.Chubanshe')),
            ],
        ),
        migrations.CreateModel(
            name='Jiaocai',
            fields=[
                ('jc_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('jc_name', models.CharField(max_length=10)),
                ('zuozhe', models.CharField(max_length=10)),
                ('danjia', models.IntegerField()),
                ('chubanshe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_ks.Chubanshe')),
            ],
        ),
        migrations.CreateModel(
            name='Xuexiao',
            fields=[
                ('xx_id', models.IntegerField(primary_key=True, serialize=False)),
                ('xx_name', models.CharField(max_length=10)),
                ('chubanshe', models.ManyToManyField(to='test_ks.Chubanshe')),
                ('dinggou', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_ks.Dinggou')),
            ],
        ),
    ]
