# Generated by Django 2.1.15 on 2019-12-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jiaocai',
            name='chubanshe',
        ),
        migrations.AddField(
            model_name='jiaocai',
            name='chubanshe',
            field=models.ManyToManyField(to='test_ks.Chubanshe'),
        ),
    ]
