# Generated by Django 2.1.15 on 2019-12-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ks', '0002_auto_20191231_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinggou',
            name='jc_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='教材号'),
        ),
    ]
