# Generated by Django 2.1.15 on 2019-12-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ks', '0003_auto_20191231_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chubanshe',
            options={'verbose_name': '出版社表', 'verbose_name_plural': '出版社表'},
        ),
        migrations.AlterModelOptions(
            name='dinggou',
            options={'verbose_name': '订购表', 'verbose_name_plural': '订购表'},
        ),
        migrations.AlterModelOptions(
            name='jiaocai',
            options={'verbose_name': '教材表', 'verbose_name_plural': '教材表'},
        ),
        migrations.AlterModelOptions(
            name='xuexiao',
            options={'verbose_name': '学校表', 'verbose_name_plural': '学校表'},
        ),
        migrations.AlterField(
            model_name='chubanshe',
            name='cbs_kucun',
            field=models.IntegerField(null=True, verbose_name='库存量'),
        ),
        migrations.AlterField(
            model_name='chubanshe',
            name='cbs_name',
            field=models.CharField(max_length=10, verbose_name='出版社名'),
        ),
        migrations.AlterField(
            model_name='dinggou',
            name='dg_dgliang',
            field=models.IntegerField(verbose_name='订购量'),
        ),
        migrations.AlterField(
            model_name='dinggou',
            name='dg_dhliang',
            field=models.IntegerField(null=True, verbose_name='到货量'),
        ),
        migrations.AlterField(
            model_name='dinggou',
            name='dg_lyliang',
            field=models.IntegerField(null=True, verbose_name='领用量'),
        ),
        migrations.AlterField(
            model_name='jiaocai',
            name='danjia',
            field=models.IntegerField(verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='jiaocai',
            name='zuozhe',
            field=models.CharField(max_length=10, verbose_name='作者'),
        ),
    ]
