# Generated by Django 2.1.15 on 2019-12-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ks', '0004_auto_20191231_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chubanshe',
            name='cbs_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='出版社号'),
        ),
        migrations.AlterField(
            model_name='chubanshe',
            name='jc_id',
            field=models.CharField(max_length=10, verbose_name='教材号'),
        ),
        migrations.AlterField(
            model_name='dinggou',
            name='cbs_id',
            field=models.IntegerField(verbose_name='出版社号'),
        ),
        migrations.AlterField(
            model_name='dinggou',
            name='xx_id',
            field=models.IntegerField(verbose_name='学校号'),
        ),
        migrations.AlterField(
            model_name='jiaocai',
            name='jc_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='教材号'),
        ),
        migrations.AlterField(
            model_name='jiaocai',
            name='jc_name',
            field=models.CharField(max_length=10, verbose_name='教材名'),
        ),
        migrations.AlterField(
            model_name='xuexiao',
            name='xx_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='学校号'),
        ),
        migrations.AlterField(
            model_name='xuexiao',
            name='xx_name',
            field=models.CharField(max_length=10, verbose_name='学校名'),
        ),
    ]
