# Generated by Django 2.1.15 on 2020-01-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_ks', '0006_auto_20200102_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chubanshe',
            name='jc_id',
        ),
    ]
