# Generated by Django 2.1.15 on 2020-01-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ks', '0007_remove_chubanshe_jc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiaocai',
            name='cbs_name',
            field=models.CharField(max_length=10, null=True, verbose_name='出版社名'),
        ),
    ]
