# Generated by Django 2.1.15 on 2020-01-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ks', '0010_auto_20200102_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chubanshe',
            name='cbs_name',
            field=models.CharField(max_length=20, verbose_name='出版社名'),
        ),
        migrations.AlterField(
            model_name='jiaocai',
            name='cbs_name',
            field=models.CharField(max_length=20, null=True, verbose_name='出版社名'),
        ),
        migrations.AlterField(
            model_name='jiaocai',
            name='jc_name',
            field=models.CharField(max_length=20, verbose_name='教材名'),
        ),
        migrations.AlterField(
            model_name='jiaocai',
            name='zuozhe',
            field=models.CharField(max_length=20, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='xuexiao',
            name='xx_name',
            field=models.CharField(max_length=20, verbose_name='学校名'),
        ),
    ]
